module.exports = {
  Foundation: [
    // "Array",
    // "ByteCountFormatter",
    // "Calendar",
    // "CharacterSet",
    // "CollectionDifference",
    // "Data",
    // "Date",
    // "DateComponents",
    // "DateComponentsFormatter",
    // "DateFormatter",
    // "DateInterval",
    // "DateIntervalFormatter",
    // "Decimal",
    // "Dictionary",
    // "EnergyFormatter",
    // "FileManager.DirectoryEnumerator",
    // "FileManager",
    // "Formatter",
    // "IndexPath",
    // "IndexSet",
    // "InputStream",
    // "ISO8601DateFormatter",
    // "LengthFormatter",
    // "ListFormatter",
    // "Locale",
    // "MassFormatter",
    // "Measurement",
    // "MeasurementFormatter",
    // "NetService",
    // "Notification",
    // "NSAppleEventManager",
    // "NSAutoreleasePool",
    // "NSBundleResourceRequest",
    // "NSCache",
    // "NSCalendarDate",
    // "NSCoder",
    // "NSConditionLock",
    // "NSConnection",
    // "NSConstantString",
    // "NSCountedSet",
    // "NSDistantObject",
    // "NSDistantObjectRequest",
    // "NSDistributedLock",
    // "NSEnumerator",
    // "NSExpression",
    // "NSGarbageCollector",
    // "NSHashTable",
    // "NSInvocation",
    // "NSInvocationOperation",
    // "NSKeyedArchiver",
    // "NSKeyedUnarchiver",
    // "NSLinguisticTagger",
    // "NSLock",
    // "NSMachBootstrapServer",
    // "NSMapTable",
    // "NSMessagePortNameServer",
    // "NSMethodSignature",
    // "NSMutableArray",
    // "NSMutableCharacterSet",
    // "NSMutableData",
    // "NSMutableDictionary",
    // "NSMutableIndexSet",
    // "NSMutableOrderedSet",
    // "NSMutableSet",
    // "NSMutableString",
    // "NSMutableURLRequest",
    // "NSNumber",
    // "NSOrderedCollectionChange",
    // "NSOrderedSet",
    // "NSPortCoder",
    // "NSPortNameServer",
    // "NSProtocolChecker",
    // "NSProxy",
    // "NSPurgeableData",
    // "NSRecursiveLock",
    // "NSScriptCommandDescription",
    // "NSSimpleCString",
    // "NSSocketPortNameServer",
    // "NSUnitInformationStorage",
    // "NSURLSessionWebSocketMessage",
    // "NSXPCCoder",
    // "NSXPCInterface",
    // "NumberFormatter",
    // "OutputStream",
    // "PersonNameComponents",
    // "PersonNameComponentsFormatter",
    // "PortMessage",
    // "Progress",
    // "RelativeDateTimeFormatter",
    // "RunLoop",
    // "Scanner",
    // "Set",
    // "SocketPort",
    // "String",
    // "TimeZone",
    // "URL",
    // "URLComponents",
    // "URLCredential",
    // "URLProtectionSpace",
    // "URLQueryItem",
    // "URLRequest",
    // "URLSessionTaskTransactionMetrics",
    // "UUID",

    "NSAffineTransform",
    "BlockOperation",
    "Bundle",
    "CachedURLResponse",
    "Dimension",
    "DistributedNotificationCenter",
    "Error",
    "FileHandle",
    "FileWrapper",
    "Host",
    "HTTPCookie",
    "HTTPCookieStorage",
    "HTTPURLResponse",
    "JSONSerialization",
    "MessagePort",
    "NetServiceBrowser",
    "NotificationCenter",
    "NotificationQueue",
    "NSAppleEventDescriptor",
    "NSAppleScript",
    "NSAssertionHandler",
    "NSAttributedString",
    "NSBackgroundActivityScheduler",
    "NSClassDescription",
    "NSCloneCommand",
    "NSCloseCommand",
    "NSComparisonPredicate",
    "NSCompoundPredicate",
    "NSCondition",
    "NSCountCommand",
    "NSCreateCommand",
    "NSDataDetector",
    "NSDecimalNumberHandler",
    "NSDeleteCommand",
    "NSException",
    "NSExistsCommand",
    "NSExtensionContext",
    "NSExtensionItem",
    "NSFileAccessIntent",
    "NSFileCoordinator",
    "NSFileProviderService",
    "NSFileSecurity",
    "NSFileVersion",
    "NSGetCommand",
    "NSIndexSpecifier",
    "NSItemProvider",
    "NSLogicalTest",
    "NSMachPort",
    "NSMetadataItem",
    "NSMetadataQuery",
    "NSMetadataQueryAttributeValueTuple",
    "NSMetadataQueryResultGroup",
    "NSMiddleSpecifier",
    "NSMoveCommand",
    "NSMutableAttributedString",
    "NSNameSpecifier",
    "NSNull",
    "NSOrthography",
    "NSPointerArray",
    "NSPointerFunctions",
    "NSPositionalSpecifier",
    "NSPredicate",
    "NSPropertySpecifier",
    "NSQuitCommand",
    "NSRandomSpecifier",
    "NSRangeSpecifier",
    "NSRegularExpression",
    "NSRelativeSpecifier",
    "NSScriptClassDescription",
    "NSScriptCoercionHandler",
    "NSScriptCommand",
    "NSScriptExecutionContext",
    "NSScriptObjectSpecifier",
    "NSScriptSuiteRegistry",
    "NSScriptWhoseTest",
    "NSSecureUnarchiveFromDataTransformer",
    "NSSetCommand",
    "NSSortDescriptor",
    "NSSpecifierTest",
    "NSSpellServer",
    "NSTextCheckingResult",
    "NSUbiquitousKeyValueStore",
    "NSUniqueIDSpecifier",
    "NSURLConnection",
    "NSURLDownload",
    "NSURLHandle",
    "NSUserActivity",
    "NSUserAppleScriptTask",
    "NSUserAutomatorTask",
    "NSUserNotification",
    "NSUserNotificationAction",
    "NSUserNotificationCenter",
    "NSUserScriptTask",
    "NSUserUnixTask",
    "NSValue",
    "NSWhoseSpecifier",
    "NSXPCConnection",
    "NSXPCListener",
    "NSXPCListenerEndpoint",
    "Operation",
    "OperationQueue",
    "Pipe",
    "Port",
    "Process",
    "ProcessInfo",
    "PropertyListSerialization",
    "Stream",
    "Thread",
    "Timer",
    "UndoManager",
    "Unit",
    "UnitAcceleration",
    "UnitAngle",
    "UnitArea",
    "UnitConcentrationMass",
    "UnitConverter",
    "UnitConverterLinear",
    "UnitDispersion",
    "UnitDuration",
    "UnitElectricCharge",
    "UnitElectricCurrent",
    "UnitElectricPotentialDifference",
    "UnitElectricResistance",
    "UnitEnergy",
    "UnitFrequency",
    "UnitFuelEfficiency",
    "UnitIlluminance",
    "UnitLength",
    "UnitMass",
    "UnitPower",
    "UnitPressure",
    "UnitSpeed",
    "UnitTemperature",
    "UnitVolume",
    "URLAuthenticationChallenge",
    "URLCache",
    "URLCredentialStorage",
    "URLProtocol",
    "URLResponse",
    "URLSession",
    "URLSessionConfiguration",
    "URLSessionDataTask",
    "URLSessionDownloadTask",
    "URLSessionStreamTask",
    "URLSessionTask",
    "URLSessionTaskMetrics",
    "URLSessionUploadTask",
    "URLSessionWebSocketTask",
    "UserDefaults",
    "ValueTransformer",
    "XMLDocument",
    "XMLDTD",
    "XMLDTDNode",
    "XMLElement",
    "XMLNode",
    "XMLParser"
  ],
  AppKit: [
    // "NSAccessibilityCustomAction",
    // "NSAccessibilityCustomRotorItemResult",
    // "NSAccessibilityCustomRotorSearchParameters",
    // "NSAccessibilityElement",
    // "NSArrayController",
    // "NSATSTypesetter",
    // "NSCandidateListTouchBarItem",
    // "NSCollectionViewDiffableDataSource",
    // "NSCollectionViewDiffableDataSourceReference",
    // "NSCollectionViewFlowLayoutInvalidationContext",
    // "NSCollectionViewLayoutInvalidationContext",
    // "NSDictionaryController",
    // "NSDiffableDataSourceSnapshot",
    // "NSDiffableDataSourceSnapshotReference",
    // "NSEvent",
    // "NSFont",
    // "NSFontManager",
    // "NSGradient",
    // "NSObjectController",
    // "NSPathCell",
    // "NSPDFInfo",
    // "NSPrintInfo",
    // "NSPrintPanel",
    // "NSRulerMarker",
    // "NSSliderTouchBarItem",
    // "NSSpellChecker",
    // "NSTextContainer",
    // "NSTouch",
    // "NSTrackingArea",
    // "NSTreeController",
    // "NSTreeNode",
    // "NSTypesetter",
    // "NSWindowController",
    // "NSWorkspace",
    // "NSWorkspaceAuthorization",
    // "NSWorkspaceOpenConfiguration",


    //
    // AppKit
    //

    "Box",
    "Browser",
    "Button",
    "ClipView",
    "CollectionView",
    "ColorWell",
    "ComboBox",
    "Control",
    "DatePicker",
    "GridView",
    "ImageView",
    "LevelIndicator",
    "Matrix",
    "NSAccessibilityCustomRotor",
    "NSActionCell",
    "NSAlert",
    "NSAlignmentFeedbackFilter",
    "NSAnimation",
    "NSAnimationContext",
    "NSAppearance",
    "NSApplication",
    "NSBezierPath",
    "NSBindingSelectionMarker",
    "NSBitmapImageRep",
    "NSBrowserCell",
    "NSButtonCell",
    "NSButtonTouchBarItem",
    "NSCell",
    "NSCIImageRep",
    "NSClickGestureRecognizer",
    "NSCollectionLayoutAnchor",
    "NSCollectionLayoutBoundarySupplementaryItem",
    "NSCollectionLayoutDecorationItem",
    "NSCollectionLayoutDimension",
    "NSCollectionLayoutEdgeSpacing",
    "NSCollectionLayoutGroup",
    "NSCollectionLayoutGroupCustomItem",
    "NSCollectionLayoutItem",
    "NSCollectionLayoutSection",
    "NSCollectionLayoutSize",
    "NSCollectionLayoutSpacing",
    "NSCollectionLayoutSupplementaryItem",
    "NSCollectionViewCompositionalLayout",
    "NSCollectionViewCompositionalLayoutConfiguration",
    "NSCollectionViewFlowLayout",
    "NSCollectionViewGridLayout",
    "NSCollectionViewItem",
    "NSCollectionViewLayout",
    "NSCollectionViewLayoutAttributes",
    "NSCollectionViewTransitionLayout",
    "NSCollectionViewUpdateItem",
    "NSColor",
    "NSColorList",
    "NSColorPanel",
    "NSColorPicker",
    "NSColorPickerTouchBarItem",
    "NSColorSampler",
    "NSColorSpace",
    "NSComboBoxCell",
    "NSController",
    "NSCursor",
    "NSCustomImageRep",
    "NSCustomTouchBarItem",
    "NSDataAsset",
    "NSDatePickerCell",
    "NSDictionaryControllerKeyValuePair",
    "NSDocument",
    "NSDraggingItem",
    "NSDocumentController",
    "NSDockTile",
    "NSDraggingImageComponent",
    "NSDraggingSession",
    "NSEPSImageRep",
    "NSFilePromiseProvider",
    "NSFilePromiseReceiver",
    "NSFontAssetRequest",
    "NSFontCollection",
    "NSFontDescriptor",
    "NSFontPanel",
    "NSFormCell",
    "NSGestureRecognizer",
    "NSGlyphGenerator",
    "NSGlyphInfo",
    "NSGraphicsContext",
    "NSGridCell",
    "NSGridColumn",
    "NSGridRow",
    "NSGroupTouchBarItem",
    "NSHapticFeedbackManager",
    "NSHelpManager",
    "NSImage",
    "NSImageCell",
    "NSImageRep",
    "NSLayoutAnchor",
    "NSLayoutConstraint",
    "NSLayoutDimension",
    "NSLayoutGuide",
    "NSLayoutManager",
    "NSLayoutXAxisAnchor",
    "NSLayoutYAxisAnchor",
    "NSLevelIndicatorCell",
    "NSMagnificationGestureRecognizer",
    "NSMediaLibraryBrowserController",
    "NSMenu",
    "NSMenuItem",
    "NSMenuItemCell",
    "NSMenuToolbarItem",
    "NSMutableFontCollection",
    "NSMutableParagraphStyle",
    "NSNib",
    "NSOpenPanel",
    "NSPageController",
    "NSPageLayout",
    "NSPanel",
    "NSPanGestureRecognizer",
    "NSParagraphStyle",
    "NSPasteboard",
    "NSPasteboardItem",
    "NSPathComponentCell",
    "NSPathControlItem",
    "NSPDFImageRep",
    "NSPDFPanel",
    "NSPersistentDocument",
    "NSPickerTouchBarItem",
    "NSPICTImageRep",
    "NSPopover",
    "NSPopoverTouchBarItem",
    "NSPopUpButtonCell",
    "NSPredicateEditorRowTemplate",
    "NSPressGestureRecognizer",
    "NSPressureConfiguration",
    "NSPrinter",
    "NSPrintOperation",
    "NSResponder",
    "NSRotationGestureRecognizer",
    "NSRunningApplication",
    "NSSavePanel",
    "NSScreen",
    "NSScrubberFlowLayout",
    "NSScrubberLayout",
    "NSScrubberLayoutAttributes",
    "NSScrubberProportionalLayout",
    "NSScrubberSelectionStyle",
    "NSSearchFieldCell",
    "NSSecureTextFieldCell",
    "NSSegmentedCell",
    "NSShadow",
    "NSSharingService",
    "NSSharingServicePicker",
    "NSSharingServicePickerToolbarItem",
    "NSSharingServicePickerTouchBarItem",
    "NSSliderAccessory",
    "NSSliderAccessoryBehavior",
    "NSSliderCell",
    "NSSound",
    "NSSpeechRecognizer",
    "NSSpeechSynthesizer",
    "NSSplitViewController",
    "NSSplitViewItem",
    "NSStatusBar",
    "NSStatusItem",
    "NSStepperCell",
    "NSStepperTouchBarItem",
    "NSStoryboard",
    "NSStoryboardSegue",
    "NSStringDrawingContext",
    "NSTableColumn",
    "NSTableHeaderCell",
    "NSTableViewRowAction",
    "NSTabViewController",
    "NSTabViewItem",
    "NSTextAlternatives",
    "NSTextAttachment",
    "NSTextAttachmentCell",
    "NSTextBlock",
    "NSTextCheckingController",
    "NSTextFieldCell",
    "NSTextFinder",
    "NSTextInputContext",
    "NSTextList",
    "NSTextStorage",
    "NSTextTab",
    "NSTextTable",
    "NSTextTableBlock",
    "NSTitlebarAccessoryViewController",
    "NSTokenFieldCell",
    "NSToolbar",
    "NSToolbarItem",
    "NSToolbarItemGroup",
    "NSTouchBar",
    "NSTouchBarItem",
    "NSUserDefaultsController",
    "NSUserInterfaceCompressionOptions",
    "NSView",
    "NSViewAnimation",
    "NSViewController",
    "NSWindow",
    "NSWindowTab",
    "NSWindowTabGroup",
    "OutlineView",
    "PathControl",
    "PopUpButton",
    "PredicateEditor",
    "ProgressIndicator",
    "RuleEditor",
    "RulerView",
    "Scroller",
    "ScrollView",
    "Scrubber",
    "ScrubberArrangedView",
    "ScrubberImageItemView",
    "ScrubberItemView",
    "ScrubberSelectionView",
    "ScrubberTextItemView",
    "SearchField",
    "SecureTextField",
    "SegmentedControl",
    "Slider",
    "SplitView",
    "StackView",
    "StatusBarButton",
    "Stepper",
    "Switch",
    "TableCellView",
    "TableHeaderView",
    "TableRowView",
    "TableView",
    "TabView",
    "Text",
    "TextField",
    "TextView",
    "TokenField",
    "VisualEffectView"
  ]
}
